# Generated by Django 4.0.6 on 2022-07-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lewis_structures_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atom",
            name="element_symbol",
            field=models.CharField(max_length=3),
        ),
    ]
