# Generated by Django 4.0.6 on 2022-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lewis_structures_app", "0003_alter_atom_element_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="atom",
            name="name",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
