# Generated by Django 4.0.6 on 2022-07-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lewis_structures_app', '0004_atom_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atom',
            options={'ordering': ['atom_id']},
        ),
        migrations.AlterField(
            model_name='electron',
            name='is_paired',
            field=models.BooleanField(default=None),
        ),
    ]
