# Generated by Django 4.0.6 on 2022-07-27 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "lewis_structures_app",
            "0006_electron_paired_with_electron_starting_is_paired",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="electron",
            name="paired_with",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lewis_structures_app.electron",
            ),
        ),
    ]
