# Generated by Django 4.0.6 on 2022-07-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lewis_structures_app", "0008_alter_electron_is_paired_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electron",
            name="paired_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lewis_structures_app.electron",
            ),
        ),
    ]
