# Generated by Django 4.0.6 on 2022-07-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lewis_structures_app", "0011_alter_electron_starting_is_paired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electron",
            name="paired_with",
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
