# Generated by Django 4.0.6 on 2022-07-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lewis_structures_app", "0012_alter_electron_paired_with"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="electron",
            name="paired_with",
        ),
    ]
